# Generated by Django 4.0.4 on 2022-04-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'managed': False},
        ),
    ]
