# Generated by Django 4.0.4 on 2022-04-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
    ]
