# Generated by Django 4.0.4 on 2022-04-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='board_board',
        ),
    ]
